classifier:
  default_params:
    n_estimators: 400
    learning_rate: 0.05
    max_depth: 4
    subsample: 0.4
    colsample_bytree: 0.4
    gamma: 0
    reg_alpha: 5.0
    reg_lambda: 5.0

  params_dist:
    n_estimators: [50, 100, 1000]
    learning_rate: [0.02, 0.05]
    max_depth: [3, 6, 9]
    subsample: [0.6, 0.8]
    colsample_bytree: [0.6, 0.8]
    reg_alpha: [0.0, 1.0]
    reg_lambda: [0.0, 0.1]

regressor:
  default_params:
    n_estimators: 400
    learning_rate: 0.03
    max_depth: 4
    subsample: 0.4
    colsample_bytree: 0.8
    gamma: 0
    reg_alpha: 5.0
    reg_lambda: 5.0

  params_dist:
    n_estimators: [100, 500, 1000]
    learning_rate: [0.02, 0.05]
    max_depth: [3, 6, 9]
    subsample: [0.6, 0.8]
    colsample_bytree: [0.6, 0.8]
    reg_alpha: [0.0, 1.0]
    reg_lambda: [0.0, 0.1]