# H9 StPetersberg only

data_path: data/H9_StPetersberg_only_2.csv
output_path: outputs/StPetersberg_only

label_names:
  - BT

class_target_cols:
  - Bin_Both

reg_target_cols:
  - VolBoth_sum

drop_cols:
  # Repetitive/Identifier Features
  - GRID_ID
  - num_story_med
  - num_story_sum
  - sqft_med
  - sqft_sum
  - found_ht_med
  - found_ht_sum
  - val_struct_med
  - val_struct_sum
  - val_cont_med
  - val_cont_sum
  - age_med

  # Targets
  - VolCD
  - VolVG
  - VolCD_sum
  - VolVG_sum
  - VolBoth_sum
  - Bin_CD
  - Bin_VG
  - Bin_Both

  # Variable Drop Features
  - fld_pct
  - bldgS
  - slope
  - occtype_COM
  - landcover

categorical_cols:
  - fld_zone
  - landcover
  - landuse
  - evac_degree

categorical_encoding:
  default: onehot
  overrides:
    landuse: target
    evac_degree: target

target_encoding_smoothing: 20.0

feature_filtering:
  enabled: true
  drop_constant: true
  min_binary_positive_count: 30
  max_dominant_value_fraction: 0.7

feature_cols_to_log:
  - sqft
  - val_struct
  - val_cont

outlier_threshold:
smote: true
scale_pos_weight: false
log_features: true
log_target_reg: false

class_default_params:
  n_estimators: 1000
  learning_rate: 0.05
  max_depth: 9
  subsample: 0.6
  colsample_bytree: 0.8
  reg_alpha: 0.0
  reg_lambda: 0.1

reg_default_params:
  n_estimators: 500
  learning_rate: 0.05
  max_depth: 3
  subsample: 0.6
  colsample_bytree: 0.8
  reg_alpha: 0.1
  reg_lambda: 1.0
