data_path: data/NSI_DEBRIS_ALL_PL.csv
output_path: output/NSI_DEBRIS_ALL_PL

class_target_cols:
  - has_veg_debris
  - has_con_debris

reg_target_cols:
  - veg_volume
  - con_volume

label_names:
  - VG
  - CD

drop_cols:
  - fd_id
  - cbfips
  - cbgfips
  - veg_volume
  - con_volume
  - has_veg_debris
  - has_con_debris

class_params_dist:
  n_estimators: [200, 600, 1000]
  learning_rate: [0.01, 0.03, 0.05, 0.1]
  max_depth: [3, 6, 9, 12]
  min_child_weight: [1, 3, 5]
  subsample: [0.3, 0.6, 0.8, 1.0]
  colsample_bytree: [0.6, 0.8, 1.0]
  reg_alpha: [0.0, 0.1, 1.0]
  reg_lambda: [0.0, 0.1, 1.0]

reg_params_dist:
  n_estimators: [100, 300, 1000]
  learning_rate: [0.03, 0.05, 0.1]
  max_depth: [3, 6, 9]
  min_child_weight: [1, 3]
  subsample: [0.6, 0.8, 1.0]
  colsample_bytree: [0.6, 0.8, 1.0]
  reg_alpha: [0.0, 0.1, 1.0]
  reg_lambda: [0.0, 0.1, 1.0]

class_default_params:
  n_estimators: 1000
  learning_rate: 0.05
  max_depth: 9
  subsample: 0.6
  colsample_bytree: 0.8
  reg_alpha: 0.0
  reg_lambda: 0.1

reg_default_params:
  n_estimators: 500
  learning_rate: 0.05
  max_depth: 3
  subsample: 0.6
  colsample_bytree: 0.8
  reg_alpha: 0.1
  reg_lambda: 1.0
